var mochaTestGenerators = require('./lib/reduxMochaTestGenerators');

exports.actionCreator = mochaTestGenerators.actionCreator;
exports.asyncActionCreator = mochaTestGenerators.asyncActionCreator;
exports.reducer = mochaTestGenerators.reducer;

exports.shouldCreateActionWithCorrectPayload = mochaTestGenerators.shouldCreateActionWithCorrectPayload;
exports.shouldDispatchCorrectActions = mochaTestGenerators.shouldDispatchCorrectActions;
exports.shouldDispatchSuccessAndFailureActions = mochaTestGenerators.shouldDispatchSuccessAndFailureActions;
exports.shouldReturnTheInitialState = mochaTestGenerators.shouldReturnTheInitialState;
exports.shouldHandleAction = mochaTestGenerators.shouldHandleAction;